#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries

if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
    mkdir $OPENSHIFT_DATA_DIR/media
fi

ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media

source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
${OPENSHIFT_PYTHON_DIR}virtenv/bin/pip install --no-index --find-links=${OPENSHIFT_REPO_DIR}libs/requirements  -r ${OPENSHIFT_REPO_DIR}libs/requirements.txt
